# Default values for gcloud-cleanup.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: gcr.io/travis-ci-prod-services-1/gcloud-cleanup
  tag: ''
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

# Pull secrets from trvs keychain
trvs:
  # If not enabled, be sure to set secretName and create a secret with the
  # necessary environment variables for gcloud-cleanup
  enabled: false
  app: "gcloud-cleanup"
  env: ""
  pro: false

secretName: ""
serviceAccountSecretName: ""

# Self-provisioned Redis through requirements.yaml
redis:
  enabled: false
  cluster:
    enabled: false
  master:
    persistence:
      enabled: false

# Cluster provided Redis Cluster (see releases/*/rate_limit_redis.yaml)
rateLimitRedis:
  enabled: false
  secretName: rate-limit-redis
  envPrefix: RATE_LIMIT_REDIS

zones: "us-central1-a,us-central1-b,us-central1-c,us-central1-f"
