---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault-kubernetes-synchronizer
  namespace: gce-staging-services-1
  labels:
    appl: vault-kubernetes-synchronizer
spec:
  replicas: 1
  selector:
    matchLabels:
      appl: vault-kubernetes-synchronizer
  template:
    metadata:
      labels:
        appl: vault-kubernetes-synchronizer
    spec:
      serviceAccountName: vault-auth
      volumes:
      - name: vault-token
        emptyDir:
          medium: Memory
      initContainers:
      - name: vault-kubernetes-authenticator
        image: postfinance/vault-kubernetes-authenticator:0.1.4
        imagePullPolicy: Always
        volumeMounts:
        - name: vault-token
          mountPath: /home/vault
        env:
        - name: VAULT_ADDR
          value: http://vault-staging.gce-staging-services-1.svc.cluster.local:8200
        - name: VAULT_SKIP_VERIFY
          value: "true"
        - name: VAULT_AUTH_MOUNT_PATH
          value: kubernetes
        - name: VAULT_ROLE
          value: vault-auth
        - name: VAULT_TOKEN_PATH
          value: /home/vault/.vault-token
        - name: ALLOW_FAIL
          value: "true"
      containers:
      - name: vault-kubernetes-synchronizer
        image: gcr.io/travis-ci-staging-services-1/vault-kubernetes-synchronizer:0.1.4-1-loop
        imagePullPolicy: Always
        volumeMounts:
        - name: vault-token
          mountPath: /home/vault
        env:
        - name: VAULT_ADDR
          value: http://vault-staging.gce-staging-services-1.svc.cluster.local:8200
        - name: VAULT_SKIP_VERIFY
          value: "true"
        - name: VAULT_TOKEN_PATH
          value: /home/vault/.vault-token
        - name: VAULT_SECRETS
          value: secret/data/test-webhook-nodered
