---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: memcached
  namespace: gce-staging-services-1
spec:
  chart:
    repository: https://charts.helm.sh/stable
    name: memcached
    version: 3.2.2
  releaseName: memcached
