---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: rabbitmq-ha
  namespace: gce-staging-services-1
spec:
  chart:
    repository: https://charts.helm.sh/stable
    name: rabbitmq-ha
    version: 1.32.3
  releaseName: rabbitmq-ha
