---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: redis
  namespace: gce-staging-services-1
spec:
  chart:
    repository: https://charts.helm.sh/stable
    name: redis
    version: 9.1.7
  releaseName: redis
  values:
    cluster:
      enabled: false
    master:
      persistence:
        enabled: false
