apiVersion: apps/v1
kind: Deployment
metadata:
  name: secrets-sandbox
  namespace: gce-staging-services-1
  labels:
    app: secrets-sandbox
spec:
  selector:
    matchLabels:
      app: secrets-sandbox
  replicas: 1
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/agent-inject-status: "update"
        vault.hashicorp.com/agent-inject-secret-test-webhook-nodered: "secret/data/test-webhook-nodered"
        vault.hashicorp.com/role: "heroku-config-vars-sync"
      labels:
        app: secrets-sandbox
    spec:
      serviceAccountName: heroku-config-vars-sync
      containers:
      - name: nginx
        image: nginx
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: heroku-config-vars-sync
  namespace: gce-staging-services-1
  labels:
    app: secrets-sandbox

