---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: docker-redis
  namespace: default
spec:
  chart:
    repository: https://charts.helm.sh/stable
    name: redis
    version: 8.0.13
  releaseName: docker-redis
  values:
    cluster:
      enabled: false
    master:
      persistence:
        enabled: false
