apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: worker-premium-gpu
  namespace: default
spec:
  chart:
    path: charts/gce-worker
    git: git@github.com:travis-ci/kubernetes-config.git
    ref: staging
  releaseName: worker-premium-gpu
  values:
    image:
      repository: gcr.io/travis-staging-1/worker
      tag: v6.2.22
      # Example calculation: 2400 CPUs / 2 vCPU per job = 1200 maxJobs
      # Staging doesn't need that much, would be a waste of resources.
    cluster:
      enabled: true
      maxJobs: 5
      maxJobsPerWorker: 5

    site: com
    queue: builds.gce-premium-gpu
    project: travis-staging-1
    librato_source_prefix: staging-1-gce

    trvs:
      enabled: true
      app: gce-workers
      env: staging-1
      pro: true

    rateLimitRedis:
      enabled: true
      secretName: rate-limit-redis
      envPrefix: RATE_LIMIT_REDIS
      
    default_machine_type: "n1-standard-2"
    worker_gce_zones: "us-central1-c" 
