apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: heapster
  namespace: kube-system
spec:
  chart:
    repository: https://charts.helm.sh/stable
    name: heapster
    version: "0.3.2"
  releaseName: heapster
  values:
    rbac:
      create: true
    command:
      - /heapster
      - "--source=kubernetes.summary_api:https://kubernetes.default?kubeletHttps=true&kubeletPort=10250&insecure=true"
      - "--sink=statsd:udp://statsd:8125?prefix=kubernetes.macstadium-prod-1&allowedLabels=container_name,namespace_name,pod_name,type,hostname,nodename"
