apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "macbot.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "macbot.name" . }}
    helm.sh/chart: {{ include "macbot.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "macbot.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "macbot.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.macbot.image }}"
          imagePullPolicy: {{ .Values.macbot.imagePullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ include "macbot.fullname" . }}
            - secretRef:
                name: {{ include "macbot.fullname" . }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
      imagePullSecrets:
      - name: {{ .Values.imagePullSecrets }}
