apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: worker-com
  namespace: macstadium-staging
spec:
  chart:
    path: charts/macstadium-worker
    git: git@github.com:travis-ci/kubernetes-config.git
    ref: staging
  releaseName: worker-com
  values:
    image:
      tag: v6.2.22

    cluster:
      enabled: true
      maxJobs: 8
      maxJobsPerWorker: 2

    site: com
    jupiterBrainName: jupiter-brain-com

    trvs:
      enabled: true
      app: macstadium-workers
      env: staging-common
      pro: true
