{{- if .Values.autoscaling.enabled }}
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "job-board.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "job-board.name" . }}
    helm.sh/chart: {{ include "job-board.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "job-board.fullname" . }}
  minReplicas: {{ .Values.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.autoscaling.maxReplicas }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: {{ .Values.autoscaling.targetAverageCPUUtilization }}
  # - type: Resource
  #   resource:
  #     name: memory
  #     targetAverageValue: {{ .Values.autoscaling.targetAverageMemoryValue }}

{{- end }}
