---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: docker-registry
  namespace: gce-production-4
spec:
  chart:
    path: charts/docker-registry
    git: git@github.com:travis-ci/kubernetes-config.git
    ref: master
  releaseName: docker-registry
  values:
    replicaCount: 6
    tlsSecretName: travis-ci-com-tls-04-10-2021

    storage: gcs
    gcs:
      bucket: travis-docker-registry-central
      keyfile: /etc/docker/gcs/keyfile
      keyfileSecretName: docker-registry-keyfile
      credentials:
        project_id: travis-production-4

    resources:
      limits:
        cpu: 2000m
        memory: 2048Mi
      requests:
        cpu: 2000m
        memory: 2048Mi

    service:
      type: LoadBalancer
      loadBalancerIP: 10.40.0.200
      port: 443
      annotations:
        cloud.google.com/load-balancer-type: "Internal"

    configData:
      proxy:
        remoteurl: https://registry-1.docker.io
