---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: rate-limit-redis
  namespace: gce-production-4
spec:
  chart:
    repository: https://charts.helm.sh/stable
    name: redis
    version: 10.0.0
  releaseName: rate-limit-redis
  values:
    cluster:
      enabled: false
    master:
      persistence:
        enabled: false
