{{- if .Values.autoscaling.enabled }}
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "travis-api.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "travis-api.name" . }}
    helm.sh/chart: {{ include "travis-api.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "travis-api.fullname" . }}
  minReplicas: {{ .Values.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.autoscaling.maxReplicas }}
  metrics:
  {{- if .Values.autoscaling.targetAverageCPUUtilization }}
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: {{ .Values.autoscaling.targetAverageCPUUtilization }}
  {{- end }}
  {{- if .Values.autoscaling.targetAverageMemoryValue }}
  - type: Resource
    resource:
      name: memory
      targetAverageValue: {{ .Values.autoscaling.targetAverageMemoryValue }}
  {{- end }}

{{- end }}
